add-hw-2
Dolnikova/nodejs-homework-CLI pull request #1
Opened 2022-12-28 23:42 UTC by Dolnikova

Доброї ночі. Сподіваюсь, що все зроблено вірно)

2022-12-29 07:38 UTC, KhYulian commented on models/contacts.js
> +  });
Якщо використовуєте async/await, то then вже не слід використовувати. Аналогічно в інших місцях

2022-12-29 07:39 UTC, KhYulian commented on models/contacts.js
> +};
краще скористатися .filter для видалення

2022-12-29 07:40 UTC, KhYulian commented on models/contacts.js
> +};
використовуйте .find() для пошуку одного елементу масиву

2022-12-29 07:41 UTC, KhYulian commented on routes/api/contacts.js
> +  .with("email", "phone");
винесіть schema в окремий файл у папку utils/validation

2022-12-29 07:42 UTC, KhYulian commented on routes/api/contacts.js
> +      throw Error;
throw new Error(errorMessage)

2022-12-29 07:44 UTC, KhYulian commented on server.js
> +const argv = program.opts();
commander і все що з ним повязано у 2 дз не потрібен - видаляйте

2022-12-29 07:44 UTC, KhYulian requested changes
Потрібне доопрацювання

2022-12-30 22:29 UTC, Dolnikova commented on models/contacts.js
> +  });
виправлено, дякую за зауваження

2022-12-30 22:45 UTC, Dolnikova commented on models/contacts.js
> +};
виправлено, дякую за зауваження

2022-12-30 22:45 UTC, Dolnikova commented on models/contacts.js
> +};
виправлено, дякую за зауваження

2022-12-30 22:50 UTC, Dolnikova commented on routes/api/contacts.js
> +  .with("email", "phone");
виправлено, дякую за зауваження

2022-12-30 22:51 UTC, Dolnikova commented on routes/api/contacts.js
> +      throw Error;
виправлено, дякую за зауваження

2022-12-30 22:52 UTC, Dolnikova commented on server.js
> +const argv = program.opts();
виправлено, дякую за зауваження

2022-12-31 08:46 UTC, KhYulian approved these changes
Чудова робота! :heart::heart::heart:

2022-12-31 08:46 UTC, merged