add-hw-4
Dolnikova/nodejs-homework-CLI pull request #3
Opened 2023-01-20 20:27 UTC by Dolnikova

2023-01-21 18:02 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-21 18:02 UTC, KhYulian commented on models/user.js
> +  return user;
важливо не повертати password у респонсі, адже це чутлива інформація. Можете написати user.password = null перед return user;

2023-01-21 18:02 UTC, KhYulian commented on routes/api/auth.js
> +        message: `missing required ${data.error.details[0].context.key} field `,
Створіть та використовуйте кастомні помилки https://javascript.info/custom-errors

2023-01-21 18:02 UTC, KhYulian commented on routes/api/auth.js
> +        message: `missing required ${data.error.details[0].context.key} field `,
В усіх схожих випадках

2023-01-21 18:02 UTC, KhYulian commented on routes/api/auth.js
> +    res.status(409).json(error);
в catch викликайте next та передавайте помилку - next(error)

2023-01-21 18:02 UTC, KhYulian commented on routes/api/auth.js
> +    const data = userSchema.validate(req.body);
Для валідації краще використовувати схеми Joi та окрему middleware, яка спрацьовує перед контроллером та валідує body

2023-01-22 18:31 UTC, Dolnikova commented on models/user.js
> +  return user;
виправлено

2023-01-22 18:32 UTC, Dolnikova commented on routes/api/auth.js
> +        message: `missing required ${data.error.details[0].context.key} field `,
виправлено

2023-01-22 18:32 UTC, Dolnikova commented on routes/api/auth.js
> +    res.status(409).json(error);
виправлено

2023-01-22 18:32 UTC, Dolnikova commented on routes/api/auth.js
> +    const data = userSchema.validate(req.body);
виправлено

2023-01-23 07:50 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-23 07:50 UTC, merged